name: ci

on:
  push:
    paths:
      - 'pvz-server/**'
  pull_request:
    paths:
      - 'pvz-server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pvz-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: pvz-server/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Prisma generate
        run: npm run prisma:generate

      - name: TypeScript build
        run: npm run build
